# Alpine Linux를 베이스 이미지로 사용
FROM alpine:3.18

# NGINX 설치
RUN apk add --update nginx openssl && \
rm -rf /var/cache/apk/* && \
mkdir -p /run/nginx

# 호스트 시스템의 NGINX 설정 파일과 웹 콘텐츠를 컨테이너로 복사
COPY nginx.conf /etc/nginx/nginx.conf
COPY www /var/www

# 컨테이너가 443번 포트를 사용
EXPOSE 443

# NGINX 실행
CMD ["./init.sh"]