version: '3'
services:

  mariadb:
    container_name: mariadb
    image: mariadb:hyungjup # 태그 latest로 안나오게 하기
    env_file:
      - .env
    network:
      - docker-network
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always # MariaDB 서버가 충돌나면 자동으로 재시작
  
  wordpress:
    image: wordpress:hyungjup
    depends_on:
      - mariadb:
        condition: service_healthy
    env_file:
      - .env
    network:
      - docker-network
    volumes:
      - wp_data:/var/www/html
    ports:
      - "9000"

  nginx:
    container_name: nginx
    image: nginx:hyungjup
    env_file:
      - .env
    network:
      - docker-network
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/wordpress # WordPress 파일 볼륨
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Nginx 설정 파일