version: "3.8"

services:
    mariadb:
      image: mariadb:hyungjup
      container_name: mariadb
      build:
        context: ./requirements/mariadb
        dockerfile: Dockerfile
      env_file:
        - .env
      restart: always
      volumes:
          - db-vol:/var/lib/mysql
      expose:
        - "3306"
      networks:
        - intra
      init: true

    wordpress:
      image: wordpress:hyungjup
      container_name: wordpress
      build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
      env_file:
        - .env
      restart: always
      depends_on:
        - mariadb
      volumes:
        - wp-vol:/var/www/html
      expose:
      - "9000"
      networks:
        - intra
      init: true

    nginx:
      image: nginx:hyungjup
      container_name: nginx
      build:
        context: ./requirements/nginx
        dockerfile: Dockerfile
      depends_on:
        - wordpress
      volumes:
        - wp-vol:/var/www/html
      ports:
        - "443:443"
      networks:
        - intra
      init: true

volumes:
  db-vol:
    name: db-vol
    driver: local
  wp-vol:
    name: wp-vol
    driver: local

networks:
  intra:
    name: intra
    driver: bridge