# Alpine Linux를 베이스 이미지로 사용
FROM alpine:3.18

# NGINX, OpenSSL 설치
RUN apk update && apk add --no-cache nginx openssl

# Nginx 설정 파일 복사
COPY ./tools/nginx.conf /etc/nginx/nginx.conf

# 자체 서명된 SSL 인증서 생성(2048비트 RSA 키와 함께)
RUN mkdir -p /etc/nginx/ssl && \
	openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
	-keyout /etc/nginx/ssl/key.pem \
	-out /etc/nginx/ssl/cert.pem \
	-subj "/C=JP/ST=Tokyo/L=Minato/O=SONY, Inc./CN=sony.com"

EXPOSE 443

# Nginx 실행
CMD ["nginx", "-g", "daemon off;"]